site_name: PLATYPUS
nav:
  - ASR curation: 'index.md'
  - 'Installation and quickstart':
      - 'Installation': 'install.md'
      - 'Running example data': 'example.md'
      - 'Explanation of output' : 'output.md'
  - 'Detailed explanation':
      - 'Basic snakemake': 'basic_snakemake.md'
      - 'Snakemake diagram': 'detailed_explanation.md'
  - Customisation:
        - 'Defining files': 'defining_files.md'
        - 'Customising workflow': 'customising_workflow.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    primary: light blue
  plugins:
    - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html