site_name: PLATYPUS
nav:
  - ASR curation: 'index.md'
  - 'Project overview':
      - 'Overview': 'overview.md'
      - 'Glossary of terms' : 'glossary.md'
  - 'Specific projects':
      - 'Projects' : 'projects.md'
      - 'MBL Pilot Project': 'mbl_pilot_project.md'
  - Literature:
        - 'Annotated bibliography': 'bibliography.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
  palette:
    primary: light blue
  plugins:
    - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html